{
 "title": "Doris Overview",
 "description": "Dashboard for Apache Doris",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cluster Number",
     "type": "stat",
     "description": "Num of  Doris Clusters",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_info{type=\"is_master\"})"
      }
     ]
    },
    {
     "title": "FE Master",
     "type": "timeseries",
     "description": "Master node of FE",
     "gridPos": { "h": 7, "w": 6, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_info{component=\"fe\", type=\"is_master\"} == 1",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FE Status",
     "type": "timeseries",
     "description": "FE nodes online status",
     "gridPos": { "h": 7, "w": 7, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "up{component=\"fe\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BE status",
     "type": "timeseries",
     "description": "BE nodes online status",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "up{component=\"be\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "up{component=\"cn\"}",
       "legendFormat": "{{instance}}"
      },
      {}
     ]
    },
    {
     "title": "FE JVM Heap Stat",
     "type": "timeseries",
     "description": "The JVM heap usage percent of each Frontend of each Doris cluster.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(jvm_heap_size_bytes{component=\"fe\", type=\"used\"} * 100) by (instance, job) / sum(jvm_heap_size_bytes{component=\"fe\", type=\"max\"}) by (instance, job)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BE CPU Idle",
     "type": "timeseries",
     "description": "The Backend CPU idle overview of each Doris cluster.\nThe detail Backend CPU idle info can be seen in 'BE' section.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(rate(doris_be_cpu{mode=\"idle\"}[$__interval])) by (job)) / (sum(rate(doris_be_cpu[$__interval])) by (job))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Cluster BE Mem Stat",
     "type": "timeseries",
     "description": "The Backend memory usage overview of each Doris cluster.\nThe detail backend memory usage can be seen in 'BE' section.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(doris_be_memory_allocated_bytes) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Cluster QPS Stat",
     "type": "timeseries",
     "description": "QPS statistic group by cluster.\nThe QPS of each cluster is the sum of all queries processed on all Frontends.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job)(rate(doris_fe_query_total{component=\"fe\"}[$__interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Disk State",
     "type": "timeseries",
     "description": "The Disk state. GREEN point means this disk is ONLINE. RED point means this disk is OFFLINE",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(doris_be_disks_state{component=\"be\"} == 0)+0",
       "legendFormat": "{{instance}}: {{path}} OFFLINE"
      },
      {
       "expr": "(doris_be_disks_state{component=\"be\"} == 1)+0",
       "legendFormat": "{{instance}}: {{path}} ONLINE"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "cluster_name",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "FE Node",
     "type": "stat",
     "description": "Total Frontends node number",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(up{component=\"fe\"})"
      }
     ]
    },
    {
     "title": "FE Alive",
     "type": "stat",
     "description": "Total alive number of Frontends. Normally, it should be equal to the Total number of Frontends",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(up{component=\"fe\"}==1)"
      }
     ]
    },
    {
     "title": "BE Node",
     "type": "stat",
     "description": "Total Backends node number",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(up{component=\"be\"})"
      }
     ]
    },
    {
     "title": "BE Alive",
     "type": "stat",
     "description": "Total alive number of Backends. Normally, it should be equal to the Total number of Backends.",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(up{component=\"be\"}==1)"
      }
     ]
    },
    {
     "title": "Used Capacity",
     "type": "stat",
     "description": "Total used disk capacity of all Backends.",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(doris_be_disks_local_used_capacity)"
      }
     ]
    },
    {
     "title": "Total Capacity",
     "type": "stat",
     "description": "Total disk capacity of all Backends",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(doris_be_disks_total_capacity{component=\"be\"})"
      }
     ]
    },
    {
     "title": "Max Replayed journal id",
     "type": "timeseries",
     "description": "The max replayed meta data journal id on Frontends.\nNormally, all Frontends should be same on this metrics, or just slightly different for a short period.",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "doris_fe_max_journal_id", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Image Write",
     "type": "timeseries",
     "description": "The image wirte of each FE",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "doris_fe_image_write{type=\"success\"}",
       "legendFormat": "{{instance}}:success"
      },
      {
       "expr": "doris_fe_image_write{type=\"failed\"}",
       "legendFormat": "{{instance}}:failed"
      }
     ]
    },
    {
     "title": "Image Push",
     "type": "timeseries",
     "description": "The image push of each FE",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "doris_fe_image_push{type=\"success\"}",
       "legendFormat": "{{instance}}:success"
      },
      {
       "expr": "doris_fe_image_push{type=\"failed\"}",
       "legendFormat": "{{instance}}:failed"
      }
     ]
    },
    {
     "title": "Image Clean",
     "type": "timeseries",
     "description": "The image clean of each FE",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "doris_fe_image_clean{type=\"success\"}",
       "legendFormat": "{{instance}}:success"
      },
      {
       "expr": "doris_fe_image_clean{type=\"failed\"}",
       "legendFormat": "{{instance}}:failed"
      }
     ]
    },
    {
     "title": "BDBJE Read",
     "type": "timeseries",
     "description": "The left Y axes shows the read per seconds of journal.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "rate(doris_fe_edit_log{type=\"read\"}[$__interval])",
       "legendFormat": "{{instance}}:read-rate"
      }
     ]
    },
    {
     "title": "BDBJE Write",
     "type": "timeseries",
     "description": "The left Y axes shows write latency of 99th. The right Y axes shows the write per seconds of journal.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(doris_fe_edit_log{type=\"write\"}[$__interval])",
       "legendFormat": "{{instance}}:write-rate"
      },
      {
       "expr": "doris_fe_editlog_write_latency_ms{quantile=\"0.99\"}",
       "legendFormat": "{{instance}}:99th"
      }
     ]
    },
    {
     "title": "FE Collect Compaction Score",
     "type": "timeseries",
     "description": "The FE collect compaction score of each BE",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "doris_fe_max_tablet_compaction_score",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scheduling Tablets",
     "type": "timeseries",
     "description": "Number of tablets begin scheduled. These tablet may be in recovery process or balance process",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "doris_fe_scheduled_tablet_num", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "BE IO Util",
     "type": "timeseries",
     "description": "The max IO util of each Backend",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "doris_be_max_disk_io_util_percent",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BE Compaction Score",
     "type": "timeseries",
     "description": "The compaction score of each BE",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "doris_fe_tablet_max_compaction_score",
       "legendFormat": "{{instance}} -> {{backend}}"
      }
     ]
    },
    {
     "title": "Edit Log Size",
     "type": "timeseries",
     "description": "The edit log size for each FE",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(doris_fe_edit_log{type=\"current_bytes\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Edit Log Clean",
     "type": "timeseries",
     "description": "The edit log clean of each FE",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(doris_fe_edit_log_clean{type=\"success\"}[$__rate_interval])",
       "legendFormat": "{{instance}}:success"
      },
      {
       "expr": "rate(doris_fe_edit_log_clean{type=\"failed\"}[$__rate_interval])",
       "legendFormat": "{{instance}}:failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "description": "Requests per seconds on each Frontends.\nRequests include all requests sending to the Frontends.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(doris_fe_request_total[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "timeseries",
     "description": "Queries per seconds on each Frontends.\nQueries only include Select requests.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(doris_fe_query_total[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "99th Latency",
     "type": "timeseries",
     "description": "99 quantiles of query latency on each Frontends.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(doris_fe_query_latency_ms{quantile=\"0.99\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Query Percentile",
     "type": "timeseries",
     "description": "Left Y axes indicates 95 to 99 quantiles of query latency on each Frontends.\nRight Y axes indicates the query rate per 1 min.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(doris_fe_query_latency_ms_count[$__rate_interval])",
       "legendFormat": "{{instance}}:query-rate"
      },
      { "expr": "doris_fe_query_latency_ms", "legendFormat": "{{instance}} - {{quantile}}" }
     ]
    },
    {
     "title": "Query Error",
     "type": "timeseries",
     "description": "Left Y axes indicates the accumulated  error queries number.\nRight Y axes indicates the error query rate per 1 min.\nNormally, the error query rate should be 0.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "doris_fe_query_err", "legendFormat": "{{instance}}:err-counter" },
      {
       "expr": "rate(doris_fe_query_err[$__rate_interval])",
       "legendFormat": "{{instance}}:err-rate"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "description": "The connections' number to each Frontends.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "doris_fe_connection_total", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Broker Load Job",
     "type": "table",
     "description": "Statistic of Broker load jobs's num in each Load State.",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "doris_fe_job{type=\"BROKER\"}"
      }
     ]
    },
    {
     "title": "Insert Load Job",
     "type": "table-old",
     "description": "Statistic of load jobs's num  in each Load State which is generated by Insert Stmt.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "targets": [
      {
       "expr": "doris_fe_job{job=\"load\", type=\"INSERT\"}"
      }
     ]
    },
    {
     "title": "SC Job",
     "type": "table",
     "description": "Number of running schema change jobs.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "doris_fe_job{type=\"SCHEMA_CHANGE\"}",
       "legendFormat": "asds"
      }
     ]
    },
    {
     "title": "Rollup Job",
     "type": "table",
     "description": "Number of running rollup jobs.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "doris_fe_job{type=\"ROLLUP\"}"
      }
     ]
    },
    {
     "title": "Routine Load Job",
     "type": "table",
     "description": "Statistic of Routine load jobs's num in each Load State.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "doris_fe_job{type=\"ROUTINE_LOAD\"}"
      }
     ]
    },
    {
     "title": "Spark Load Job",
     "type": "table",
     "description": "Statistic of Spark load jobs's num in each Load State.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "doris_fe_job{type=\"SPARK\"}"
      }
     ]
    },
    {
     "title": "Broker load tendency",
     "type": "timeseries",
     "description": "The trend report of broker load job",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "doris_fe_job{job=\"load\", type=\"BROKER\", state=\"PENDING\"}",
       "legendFormat": "{{instance}}:PENDING"
      },
      {
       "expr": "doris_fe_job{job=\"load\", type=\"BROKER\", state=\"ETL\"}",
       "legendFormat": "{{instance}}:ETL"
      },
      {
       "expr": "doris_fe_job{job=\"load\", type=\"BROKER\", state=\"LOADING\"}",
       "legendFormat": "{{instance}}:LOADING"
      }
     ]
    },
    {
     "title": "Insert load tendency",
     "type": "timeseries",
     "description": "The trend report of insert load job",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "doris_fe_job{job=\"load\", type=\"INSERT\", state=\"PENDING\"}",
       "legendFormat": "{{instance}}:PENDING"
      },
      {
       "expr": "doris_fe_job{job=\"load\", type=\"INSERT\", state=\"ETL\"}",
       "legendFormat": "{{instance}}:ETL"
      },
      {
       "expr": "doris_fe_job{job=\"load\", type=\"INSERT\", state=\"LOADING\"}",
       "legendFormat": "{{instance}}:LOADING"
      }
     ]
    },
    {
     "title": "Routine load tendency",
     "type": "timeseries",
     "description": "The trend report of routine load job",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "doris_fe_job{job=\"load\", type=\"ROUTINE_LOAD\", state=\"NEED_SCHEDULE\"}",
       "legendFormat": "{{instance}}:NEED_SCHEDULE"
      },
      {
       "expr": "doris_fe_job{job=\"load\", type=\"ROUTINE_LOAD\", state=\"RUNNING\"}",
       "legendFormat": "{{instance}}:RUNNING"
      },
      {
       "expr": "doris_fe_job{job=\"load\", type=\"ROUTINE_LOAD\", state=\"PAUSED\"}",
       "legendFormat": "{{instance}}:PAUSED"
      }
     ]
    },
    {
     "title": "Spark load tendency",
     "type": "timeseries",
     "description": "The trend report of spark load job",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "doris_fe_job{job=\"load\", type=\"SPARK\", state=\"PENDING\"}",
       "legendFormat": "PENDING"
      },
      {
       "expr": "doris_fe_job{job=\"load\", type=\"SPARK\", state=\"ETL\"}",
       "legendFormat": "ETL"
      },
      {
       "expr": "doris_fe_job{job=\"load\", type=\"SPARK\", state=\"LOADING\"}",
       "legendFormat": "LOADING"
      }
     ]
    },
    {
     "title": "Report queue size",
     "type": "timeseries",
     "description": "Queue size of report in Master FE.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "doris_fe_report_queue_size", "legendFormat": "Report queue size" }
     ]
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Txn Begin/Success on FE",
     "type": "timeseries",
     "description": "Show the number and rate of txn begin and success",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "doris_fe_txn_counter{type=\"begin\"}",
       "legendFormat": "{{instance}}:txn begin"
      },
      {
       "expr": "doris_fe_txn_counter{type=\"begin\"}",
       "legendFormat": "{{instance}}:txn success"
      },
      {
       "expr": "irate(doris_fe_txn_counter{type=\"begin\"}[$__rate_interval])",
       "legendFormat": "{{instance}}:txn begin rate"
      },
      {
       "expr": "irate(doris_fe_txn_counter{type=\"begin\"}[$__rate_interval])",
       "legendFormat": "{{instance}}:txn success rate"
      }
     ]
    },
    {
     "title": "Txn Failed/Reject on FE",
     "type": "timeseries",
     "description": "Show the failed txn request. Including rejected request and failed txn",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(doris_fe_txn_counter{type=\"reject\"}[$__rate_interval])",
       "legendFormat": "{{instance}}:txn reject rate"
      },
      {
       "expr": "rate(doris_fe_txn_counter{type=\"failed\"}[$__rate_interval])",
       "legendFormat": "{{instance}}:txn failed rate"
      }
     ]
    },
    {
     "title": "Publish Task on BE",
     "type": "timeseries",
     "description": "The number of total publish task request and error rate.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(doris_be_engine_requests_total{type=\"publish\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(doris_be_engine_requests_total{type=\"publish\", status=\"failed\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fe_txn_status",
     "type": "timeseries",
     "description": "Show the txn rstatus on FE",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "doris_fe_txn_status{type=\"prepare\"}",
       "legendFormat": "{{instance}}:prepare"
      },
      {
       "expr": "doris_fe_txn_status{type=\"precommitted\"}",
       "legendFormat": "{{instance}}:precommitted"
      },
      {
       "expr": "doris_fe_txn_status{type=\"committed\"}",
       "legendFormat": "{{instance}}:committed"
      },
      {
       "expr": "doris_fe_txn_status{type=\"aborted\"}",
       "legendFormat": "{{instance}}:aborted"
      },
      {
       "expr": "doris_fe_txn_status{type=\"visible\"}",
       "legendFormat": "{{instance}}:visible"
      },
      {
       "expr": "doris_fe_txn_status{type=\"unknown\"}",
       "legendFormat": "{{instance}}:unknown"
      }
     ]
    },
    {
     "title": "Txn Load Bytes/Rows rate",
     "type": "timeseries",
     "description": "Left Y axes indicates the total received bytes rate of txn. Right Y axes indicates the loaded rows rate of txn.",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(doris_be_stream_load{type=\"receive_bytes\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}:bytes"
      },
      {
       "expr": "sum(rate(doris_be_stream_load{type=\"load_rows\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}:rows"
      }
     ]
    }
   ]
  },
  {
   "title": "FE JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "JVM Heap Used",
     "type": "timeseries",
     "description": "JVM Heap usage of specified Frontend.\nLeft Y Axes shows the used/max heap size.\nRight Y Axes shows the used percentage.",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_heap_size_bytes{component=\"fe\", type=\"used\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Heap Max",
     "type": "timeseries",
     "description": "JVM Heap usage of specified Frontend.\nLeft Y Axes shows the used/max heap size.\nRight Y Axes shows the used percentage.",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_heap_size_bytes{component=\"fe\", type=\"max\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Old",
     "type": "timeseries",
     "description": "JVM old generation usage of specified Frontend. Left Y Axes shows the used/max old generation size. Right Y Axes shows the used percentage.\nNormally, the usage percentage should be less than 80%.",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_old_size_bytes{component=\"fe\", type=\"used\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Old GC",
     "type": "graph",
     "description": "JVM full gc stat of specified Frontend. \nLeft Y Axes shows times of full gc.\nRight Y Axes shows the time cost of each full gc.",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_old_gc{component=\"fe\", type=\"count\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Young",
     "type": "graph",
     "description": "JVM young generation usage of specified Frontend.\nLeft Y Axes shows the used/max young generation size.\nRight Y Axes shows the used percentage.",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_young_size_bytes{component=\"fe\", type=\"used\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Non Heap",
     "type": "graph",
     "description": "JVM Non Heap usage of specified Frontend.\nLeft Y Axes shows the used/committed non heap size.",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_non_heap_size_bytes{component=\"fe\", type=\"used\"}",
       "legendFormat": "{{instance}}:used"
      },
      {
       "expr": "jvm_non_heap_size_bytes{component=\"fe\", type=\"committed\"}",
       "legendFormat": "{{instance}}:committed"
      }
     ]
    },
    {
     "title": "JVM Threads",
     "type": "graph",
     "description": "Num of threads of FE JVM",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_thread{component=\"fe\", type=\"count\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Young GC",
     "type": "timeseries",
     "description": "JVM young gc stat of specified Frontend. \nLeft Y Axes shows times of young gc.\nRight Y Axes shows the time cost of each young gc.",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_young_gc{component=\"fe\", type=\"count\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "BE CPU Idle",
     "type": "timeseries",
     "description": "CPU idle stat of Backends.\nLow means CPU is busy.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(rate(doris_be_cpu{mode=\"idle\"}[$__rate_interval])) by (job, instance)) / (sum(rate(doris_be_cpu[$__rate_interval])) by (job, instance)) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BE Mem",
     "type": "timeseries",
     "description": "Memory usage of Backends.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "doris_be_memory_allocated_bytes",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Net send/receive bytes",
     "type": "timeseries",
     "description": "Network send(Left Y)/receive(Right Y) bytes rate of all device except 'lo'",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(doris_be_network_send_bytes{component=\"be\", device!=\"lo\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{device}}-send"
      },
      {
       "expr": "irate(doris_be_network_receive_bytes{component=\"be\", device!=\"lo\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{device}}-receive"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "description": "Disk capacity usage of Backends",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(SUM(doris_be_disks_total_capacity{component=\"be\"}) by (instance, path) - SUM(doris_be_disks_avail_capacity{component=\"be\"}) by (instance, path)) / SUM(doris_be_disks_total_capacity{component=\"be\"}) by (instance, path)",
       "legendFormat": "{{instance}}:{{path}}"
      }
     ]
    },
    {
     "title": "Tablet Distribution",
     "type": "timeseries",
     "description": "Number of tablets of each Backends",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "doris_fe_tablet_num", "legendFormat": "{{instance}} -> {{backend}}" }
     ]
    },
    {
     "title": "BE FD(used)",
     "type": "timeseries",
     "description": "The file descriptor usage of Backends. Left Y axes shows the used fd num. Right Y axes shows the soft limit open file number.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "doris_be_process_fd_num_used", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "BE FD count (num_limit_soft)",
     "type": "timeseries",
     "description": "The file descriptor usage of Backends. Left Y axes shows the used fd num. Right Y axes shows the soft limit open file number.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "doris_be_process_fd_num_limit_soft",
       "legendFormat": "{{instance}}:soft limit"
      }
     ]
    },
    {
     "title": "Disk IO util",
     "type": "timeseries",
     "description": "IO util of Backends.\nHigh means I/O is busy.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "doris_be_max_disk_io_util_percent",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BE thread num",
     "type": "timeseries",
     "description": "The thread number of Backends",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "doris_be_process_thread_num", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "BE Compaction Cumulate",
     "type": "timeseries",
     "description": "Cumulative compaction rate of Backends.\nRight Y axes indicates the total cumulative compaction bytes.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(doris_be_compaction_bytes_total{type=\"cumulative\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BE Compaction Base",
     "type": "graph",
     "description": "Base compaction rate of Backends.\nNormally, base compaction only runs between 20:00 to 4:00 and it is configurable.\nRight Y axes indicates the total base compaction bytes.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(doris_be_compaction_bytes_total{type=\"base\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BE Scan Rows",
     "type": "timeseries",
     "description": "Scan rows rate of Backends.\nThis indicates the read rows rate when processing queries.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(doris_be_query_scan_rows[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BE Scan Bytes",
     "type": "timeseries",
     "description": "Scan rate of Backends.\nThis indicates the read rate when processing queries.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(doris_be_query_scan_bytes[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BE Push Bytes",
     "type": "timeseries",
     "description": "Loading rate of Backends.\nThis indicates the rate of file downloading in LOADING state of load job(MINI and BROKER load).\nRight Y axes indicates the total rate of file downloading.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(doris_be_push_request_write_bytes[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BE Push Rows",
     "type": "timeseries",
     "description": "Loading rows rate of Backends.\nThis indicates the rate of rows loaded in LOADING state of load job. Right Y axes shows the total push rate of cluster.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(doris_be_push_request_write_rows[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tablet Meta Write Rate",
     "type": "timeseries",
     "description": "Left Y axes shows the write rate of tablet header saved in rocksdb. Right Y axes shows the duration of each write operation.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "irate(doris_be_meta_request_total{type=\"write\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tablet Meta Write latency",
     "type": "timeseries",
     "description": "Left Y axes shows the write rate of tablet header saved in rocksdb. Right Y axes shows the duration of each write operation.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "doris_be_meta_request_duration{type=\"write\"} / doris_be_meta_request_total{type=\"write\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tablet Meta Read Rate",
     "type": "timeseries",
     "description": "Left Y axes shows the read rate of tablet header saved in rocksdb. Right Y axes shows the duration of each read operation.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "irate(doris_be_meta_request_total{type=\"read\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tablet Meta Read Rate",
     "type": "timeseries",
     "description": "Left Y axes shows the read rate of tablet header saved in rocksdb. Right Y axes shows the duration of each read operation.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "doris_be_meta_request_duration{type=\"read\"} / doris_be_meta_request_total{type=\"read\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BE tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tablets Report",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "SUM (doris_be_engine_requests_total{type=\"report_all_tablets\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(doris_be_engine_requests_total{type=\"report_all_tablets\", status=\"failed\"}[$__rate_interval])",
     "legendFormat": "Failed:{{type}} from {{instance}}"
    }
   ]
  },
  {
   "title": "Single Tablet Report",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "SUM(doris_be_engine_requests_total{type=\"report_tablet\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(doris_be_engine_requests_total{type=\"report_tablet\", status=\"failed\"}[$__rate_interval])",
     "legendFormat": "Failed:{{type}} from {{instance}}"
    }
   ]
  },
  {
   "title": "Finish Task Report",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "SUM(doris_be_engine_requests_total{type=\"finish_task\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(doris_be_engine_requests_total{status=\"failed\"}[$__rate_interval])",
     "legendFormat": "Failed:{{type}} from {{instance}}"
    }
   ]
  },
  {
   "title": "Push Task",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(doris_be_push_requests_total{status=\"SUCCESS\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(doris_be_push_requests_total{status=\"FAIL\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-failed"
    }
   ]
  },
  {
   "title": "Push Task Cost Time",
   "type": "timeseries",
   "description": "The average cost time of push tasks on each Backend.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "irate(doris_be_push_request_duration_us[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Delete",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "SUM(doris_be_engine_requests_total{type=\"delete\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(doris_be_engine_requests_total{type=\"delete\", status=\"failed\"}[$__interval])",
     "legendFormat": "{{instance}}-failed"
    }
   ]
  },
  {
   "title": "Base Compaction",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "SUM(doris_be_engine_requests_total{type=\"base_compaction\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(doris_be_engine_requests_total{type=\"base_compaction\", status=\"failed\"}[$__rate_interval])",
     "legendFormat": "{{instance}}:failed"
    }
   ]
  },
  {
   "title": "Cumulative Compaction",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "SUM(doris_be_engine_requests_total{type=\"cumulative_compaction\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(doris_be_engine_requests_total{type=\"cumulative_compaction\", status=\"failed\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Clone",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "SUM(doris_be_engine_requests_total{type=\"clone\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(doris_be_engine_requests_total{type=\"clone\", status=\"failed\"}[$__rate_interval])",
     "legendFormat": "{{instance}}:failed"
    }
   ]
  },
  {
   "title": "Create rollup",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "SUM(doris_be_engine_requests_total{type=\"create_rollup\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(doris_be_engine_requests_total{type=\"create_rollup\", status=\"failed\"}[$__rate_interval])",
     "legendFormat": "{{instance}}:failed"
    }
   ]
  },
  {
   "title": "Schema change",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "SUM(doris_be_engine_requests_total{type=\"schema_change\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(doris_be_engine_requests_total{type=\"schema_change\", status=\"failed\"}[$__rate_interval])",
     "legendFormat": "{{instance}}:failed"
    }
   ]
  },
  {
   "title": "Create tablet",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "SUM(doris_be_engine_requests_total{type=\"create_tablet\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(doris_be_engine_requests_total{type=\"create_tablet\", status=\"failed\"}[$__rate_interval])",
     "legendFormat": "{{instance}}:failed"
    }
   ]
  }
 ]
}