apiVersion: al-assad.github.io/v1beta1
kind: DorisCluster
metadata:
  name: basic
spec:
  version: 2.0.2

  fe:
    baseImage: ghcr/hs/doris-fe
    replicas: 1
    config:
      prefer_compute_node_for_external_table: "true"
    requests:
      cpu: '1'
      memory: 2Gi
      storage: 50Gi

  be:
    baseImage: ghcr.io/linsoss/doris-be
    replicas: 1
    requests:
      cpu: '1'
      memory: 1Gi
      storage: 100Gi

  cn:
    baseImage: ghcr.io/linsoss/doris-cn
    replicas: 2
    config: { }
    requests:
      cpu: '1'
      memory: 2Gi
